### ISSUE TITLE
インストールのMigrationがこける

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Install#1]
Cakeのバージョンが上がったせいか、Migrationがこけてしまうため、インストールできない。

https://github.com/CakeDC/migrations/blob/master/Lib/CakeMigration.php#L199

この箇所が、$options['precheck'] = 'Migrations.PrecheckException'のとき、$class = 'Migrations.PrecheckException'を想定しているが、$class = 'Migrations.precheckException'となってしまっていて、想定しているものと違い、エラーになっている。

<pre>
root@app:/var/www/MyShell/install# /var/www/app/app/Console/cake Migrations.migration run all -c master -i master -p NetCommons

Cake Migration Shell
---------------------------------------------------------------
Error: Migration precheck class (Migrations.PrecheckException) could not be loaded.
#0 /var/www/app/app/Plugin/Migrations/Lib/MigrationVersion.php(286): CakeMigration->__construct(Array)
#1 /var/www/app/app/Plugin/Migrations/Lib/MigrationVersion.php(379): MigrationVersion->getMigration('001_init_migrat...', 'InitMigrations', 'Migrations')
#2 /var/www/app/app/Plugin/Migrations/Lib/MigrationVersion.php(107): MigrationVersion->_initMigrations()
#3 /var/www/app/app/Plugin/Migrations/Console/Command/MigrationShell.php(105): MigrationVersion->__construct(Array)
#4 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Console/Shell.php(436): MigrationShell->startup()
#5 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(209): Shell->runCommand('run', Array)
#6 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/app/app/Console/cake.php(35): ShellDispatcher::run(Array)
#8 {main}
</pre>

後々、修正されると思うので、MigrationをForkして、暫定対応。以下の設定をクリアして、問題のelseにはいらないように対応。
https://github.com/s-nakajima/migrations/commit/f6a34c4bfc9909175798c0016f75d57717aebe03
https://github.com/s-nakajima/migrations/commit/ef67cda922d2fff0588d8f547bee3de02dbd9e24

**Comment by s-nakajima** [comment]
CakePHP2.6.5固定にするように修正
